version: "3.0"
services:
  ewp-registry:
    container_name: ewp-registry
    hostname: ewp-registry
    image: ghcr.io/erasmus-without-paper/ewp-registry-service/ewp-registry-service:latest
    entrypoint: 
      - "/root/entrypoint.sh"
    networks:
      - dev
    environment:
      - SERVER_PORT=${EWP_REGISTRY_PORT}
    ports:
      - ${EWP_REGISTRY_PORT}:${EWP_REGISTRY_PORT}
    volumes:
      - ${PWD}/docker/registry/dev/data:/root
      - ${PWD}/backend/src/main/resources/keystore/localhost.p12:/opt/keystore.p12:ro

networks:
  dev: