version: "3.0"
services:
  ewp-node:
    container_name: ewp-node
    hostname: ewp-node
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - dev
    environment:
      - REGISTRY_URL=ewp-registry:${EWP_REGISTRY_PORT}
    ports:
      - ${EWP_NODE_EXTERNAL_PORT}:8443
      # Debug port
      - ${EWP_NODE_EXTERNAL_DEBUG_PORT}:5005
    volumes:
      - ${PWD}/backend/src/main/resources/application-dev.yml:/config/application-dev.yml:ro
      - ${PWD}/${EWP_NODE_RELATIVE_PLUGINS_PATH}:/plugins

  ewp-registry:
    container_name: ewp-registry
    hostname: ewp-registry
    image: ghcr.io/erasmus-without-paper/ewp-registry-service/ewp-registry-service:latest
    entrypoint: 
      - "/root/entrypoint.sh"
    networks:
      - dev
    environment:
      - SERVER_PORT=${EWP_REGISTRY_PORT}
    ports:
      - ${EWP_REGISTRY_PORT}:${EWP_REGISTRY_PORT}
    depends_on:
      - ewp-node
    volumes:
      - ${PWD}/docker/registry/dev/data:/root
      - ${PWD}/backend/src/main/resources/keystore/localhost.p12:/opt/keystore.p12:ro

networks:
  dev: