# Build and package
FROM maven:3-openjdk-11-slim as builder

WORKDIR /build

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
    apt-get install -y nodejs

# Compile and package
COPY . .
RUN mvn -B package -DskipTests=true

# Deploy
FROM eclipse-temurin:11-jre

RUN apt-get update && apt-get install -y --no-install-recommends wget

COPY --from=builder /build/backend/src/main/resources/keystore/localhost.p12 /root/keystore/localhost.p12
COPY --from=builder /build/delivery/target/ewp-node-*-full.jar /opt/app.jar

ENV SPRING_PROFILES_ACTIVE=dev

# Add localhost certificate to CACERTS
ENV CACERTS_STORE /opt/java/openjdk/lib/security/cacerts
RUN keytool -v -importkeystore -srckeystore /root/keystore/localhost.p12 -srcstoretype PKCS12 \
  -srcstorepass p@ssw0rd -destkeystore ${CACERTS_STORE} -deststoretype JKS -deststorepass changeit \
  -noprompt

VOLUME /plugins

EXPOSE 5005
EXPOSE 8443

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", "-jar","/opt/app.jar"]
