version: "3.0"
services:
  ewp-node-frontend:
    container_name: ewp-node-frontend
    hostname: ewp-node-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    networks:
      - dev
    ports:
      - ${EWP_NODE_FRONTEND_PORT:-4200}:4200
    volumes:
      - ${PWD}/frontend/libs:/opt/ewp-node/frontend/libs
      - ${PWD}/frontend/src:/opt/ewp-node/frontend/src

  ewp-node-backend:
    container_name: ewp-node-backend
    hostname: ewp-node-backend
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    networks:
       dev:
        aliases:
          - ewp-node
    environment:
      - REGISTRY_URL=ewp-registry:${EWP_REGISTRY_PORT:-8000}
    ports:
      - ${EWP_NODE_EXTERNAL_PORT:-8443}:8443
      # Debug port
      - ${EWP_NODE_EXTERNAL_DEBUG_PORT:-5005}:5005
    volumes:
      - ${PWD}/backend/src/main/resources/application-dev.yml:/config/application-dev.yml:ro
      - ${PWD}/${EWP_NODE_RELATIVE_PLUGINS_PATH:-plugins/}:/plugins

  ewp-registry:
    container_name: ewp-registry
    hostname: ewp-registry
    build:
      context: registry
      dockerfile: Dockerfile.dev
      args:
        - SERVER_PORT=${EWP_REGISTRY_PORT:-8000}
        - EWP_NODE_HOSTNAME=ewp-node
        - EWP_NODE_PORT=8443
        - EWP_NODE_HEI_REGEX=${EWP_REGISTRY_EWP_NODE_HEI_REGEX:-^ulisboa\.pt$}
    networks:
      - dev
    ports:
      - ${EWP_REGISTRY_PORT:-8000}:${EWP_REGISTRY_PORT:-8000}
    depends_on:
      - ewp-node-backend

networks:
  dev: