# Build and package
FROM maven:3-eclipse-temurin-17 as builder-backend

WORKDIR /opt/ewp-node

COPY pom.xml pom.xml
COPY backend/pom.xml backend/pom.xml

WORKDIR /opt/ewp-node/backend

# Download dependencies first
RUN mvn dependency:resolve

COPY backend .
RUN mvn compile

# Prepare CACERTS
ENV CACERTS_STORE /opt/java/openjdk/lib/security/cacerts
RUN mkdir -p /root/keystore && cp src/main/resources/keystore/localhost.p12 /root/keystore/localhost.p12
RUN keytool -v -importkeystore -srckeystore /root/keystore/localhost.p12 -srcstoretype PKCS12 \
  -srcstorepass p@ssw0rd -destkeystore ${CACERTS_STORE} -deststoretype JKS -deststorepass changeit \
  -noprompt

COPY backend/docker/dev/application-dev-docker.yml /config/application-dev-docker.yml

ENV SPRING_CONFIG_LOCATION=/config/
ENV SPRING_PROFILES_ACTIVE=dev,dev-docker

VOLUME /plugins

EXPOSE 5005
EXPOSE 8443

ENTRYPOINT ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
