# Base context path (should not end with slash)
baseContextPath:

# Uncomment these lines to enable SSL on Spring Boot
#server:
#  ssl:
#    key-store: <PATH to keystore>
#    key-store-password: <KEYSTORE PASSWORD>
#    key-alias: <CERTIFICATE ALIAS>
#    client-auth: want # "want" in order to allow client requests without embedded client certificate

# Database configuration for the node itself (for keystore management and others)
db:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:ewp_node__tests;DB_CLOSE_DELAY=-1
  #  url: jdbc:h2:tcp://127.0.0.1:9090/mem:ewp_node_tests;DB_CLOSE_DELAY=-1 # Uncomment this line for DB debugging (requires an H2 TCP server)
  username: sa
  password:
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    hbm2ddlAuto: create
    timeZone: Europe/Lisbon

# EWP registry configuration
registry:
  url: dev-registry.erasmuswithoutpaper.eu
  autoRefresh: true
  timeBetweenRetriesInMilliseconds: 180000
  minTimeBetweenQueries: 60000

# Security configuration
security:
  # Temporary for skipping certificate check (DEFAULT: false).
  # allowMissingClientCertificate: false

  # Configuration for the Client TLS Certificate authentication
  # If a reverse proxy does SSL termination then that reverse proxy must be
  # configured to optionally verify client certificates, passing them, if present,
  # through the header indicated by the attribute clientTls.headerName below.
  # The encoding must also be defined, whether Base64 or HEX.
  clientTls:
    # Header of the request where the certificate is embedded
    headerName: x-ssl-client-cert
    encoding: hex

  # Configuration of the keystore used for authentication (such as, HTTP Signatures)
  keyStore:
    # When true, the application will try to import the keystore of the embedded server's SSL configuration
    importFromSsl: true
    # For how long the keystore is cached locally.
    # When a new keystore is created it will take this amount of time to use the new keystore
    cacheValidityInSeconds: 60
    # Password used when generating/decoding the local keystore
    password: sample-keystore-password

cnr:
  # Frequency on which notification daemon runs to process new/pending notifications
  intervalInMilliseconds: 5000
  # Maximum number of attempts to send a notification before considering it as a failure.
  # The notification daemon uses exponential delay, on the powers of 2 (in minutes), as wait time between attempts.
  # With then 10 maximum attempts, wait time for the last attempt = 2^10 minutes = 1024 minutes ~ 17 hours
  maxNumberAttempts: 10

sync:
  mappings:
    # Frequency on which sync mapping services are executed
    # 30m * 60s * 1000ms = 1800000ms
    intervalInMilliseconds: 1800000

# Configuration of basic data to load when launching for the first time
bootstrap:
  # Hosts are bootstrapped if no host is currently defined on DB
  hosts:
    # The code of a host is used to identify the host on communications from it.
    # Namely, for the Forward EWP APIs, the JWT token produced must use as "iss" (issuer)
    # the code of the host.
    - code: sample-host
      description: Sample host
      adminEmail: admin@example.com
      adminNotes: Sample host
      adminProvider: Sample Provider (EWP Node)
      # Configuration of the Forward EWP APIs
      forwardEwpApi:
        # OPTIONAL
        # A list of clients that are able to use the Forward EWP APIs
        clients:
          # Each client has an ID and a secret.
          # The ID must be used as "iss" (issuer) of the JWT token used for authentication
          # for the Forward EWP APIs.
          # The ID must be unique among all clients, independent of the host.
          # The secret is used when generating a JWT token.
          # This secret key is used by the EWP node to assert that the received JWT token
          # was effectively produced by the client.
          # Hence, both host and EWP node must know this secret.
          - id: client-1
            secret: sample-host-forward-ewp-api-secret-1
          - id: client-2
            secret: sample-host-forward-ewp-api-secret-2
      coveredHeis:
        - schacCode: sample.edu
          names:
            - locale: pt-PT
              value: Instituição de exemplo
            - locale: en
              value: Sample institution
          otherHeiIds:
            - type: pic
              value: 123456789
            - type: erasmus
              value: S S01
            - type: erasmus-charter
              value: 123456

# swagger-ui custom path
springdoc:
  version: '@springdoc.version@'
  api-docs:
    groups:
      enabled: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

stats:
  portal:
    heiId: stats.erasmuswithoutpaper.eu

# Plugins configuration
# Here it is possible to pass configuration to a given plugin by its plugin ID.
plugins:
  # Set the path to the plugins directory
  path: plugins/

  # For instance, in the example below, a property example.key belonging to a plugin with ID
  # ewp-host-plugin-demo is defined.
  ewp-host-plugin-demo:
    example:
      key: test