package pt.ulisboa.ewp.node.service.ewp.iia;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

class ConditionsHashCalculatorTest {

  @Test
  @Disabled
  void testCalculateHashFor_ValidCooperationConditions_CorrectHashReturned() {
    // Arrange
    ConditionsHashCalculator conditionsHashCalculator = new ConditionsHashCalculator();

    String iiaGetXml = "<iias-get-response\n"
        + "    xmlns=\"https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v6/endpoints/get-response.xsd\"\n"
        + "    xmlns:c=\"https://github.com/erasmus-without-paper/ewp-specs-types-contact/tree/stable-v1\"\n"
        + "    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
        + "    xsi:schemaLocation=\"\n"
        + "        https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v6/endpoints/get-response.xsd\n"
        + "        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-iias/stable-v6/endpoints/get-response.xsd\n"
        + "    \"\n"
        + ">\n"
        + "    <!--\n"
        + "    IMPORTANT: Please see the response.xsd file for detailed requirements and\n"
        + "    descriptions of all the elements. You MUST NOT base your implementation\n"
        + "    solely on the example file.\n"
        + "    -->\n"
        + "    <iia>\n"
        + "        <partner>\n"
        + "            <hei-id>uw.edu.pl</hei-id>\n"
        + "            <iia-id>0f7a5682-faf7-49a7-9cc7-ec486c49a281</iia-id>\n"
        + "            <iia-code>983/E+/III14&amp;15</iia-code>\n"
        + "            <signing-contact>\n"
        + "                <c:contact-name>Sylwia Nowak</c:contact-name>\n"
        + "                <c:person-given-names>Sylwia</c:person-given-names>\n"
        + "                <c:person-family-name>Nowak</c:person-family-name>\n"
        + "                <c:email>email@example.com</c:email>\n"
        + "                <!-- All other Abstract Contact fields are allowed too (including the role\n"
        + "                description). -->\n"
        + "            </signing-contact>\n"
        + "            <c:contact>\n"
        + "                <c:contact-name>Jadwiga Kowalska</c:contact-name>\n"
        + "                <c:person-given-names>Jadwiga</c:person-given-names>\n"
        + "                <c:person-family-name>Kowalska</c:person-family-name>\n"
        + "                <c:email>email@example.com</c:email>\n"
        + "            </c:contact>\n"
        + "        </partner>\n"
        + "        <partner>\n"
        + "            <hei-id>hibo.no</hei-id>\n"
        + "            <iia-id>1954991</iia-id>\n"
        + "            <iia-code>2014/E+/PL/4104B</iia-code>\n"
        + "            <signing-contact>\n"
        + "                <c:contact-name>Monica Turner</c:contact-name>\n"
        + "                <c:email>email@example.com</c:email>\n"
        + "            </signing-contact>\n"
        + "            <!-- Optional other remote contacts go here, if known. -->\n"
        + "        </partner>\n"
        + "        <in-effect>true</in-effect>\n"
        + "        <cooperation-conditions>\n"
        + "\n"
        + "            <!-- Student mobility for studies. -->\n"
        + "            <student-studies-mobility-spec>\n"
        + "                <sending-hei-id>uw.edu.pl</sending-hei-id>\n"
        + "                <sending-ounit-id>140</sending-ounit-id>\n"
        + "                <!-- Optional sending-contact elements go here (if supported by the\n"
        + "                server at this level). -->\n"
        + "                <receiving-hei-id>hibo.no</receiving-hei-id>\n"
        + "                <!-- Optional receiving-contact elements go here (if supported by the\n"
        + "                server at this level). -->\n"
        + "                <receiving-academic-year-id>2014/2015</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2015/2016</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2016/2017</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2017/2018</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2018/2019</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2019/2020</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2020/2021</receiving-academic-year-id>\n"
        + "                <mobilities-per-year>2</mobilities-per-year>\n"
        + "                <recommended-language-skill>\n"
        + "                    <language>en</language>\n"
        + "                    <cefr-level>B1</cefr-level>\n"
        + "                </recommended-language-skill>\n"
        + "                <recommended-language-skill>\n"
        + "                    <language>no</language>\n"
        + "                    <cefr-level>B1</cefr-level>\n"
        + "                </recommended-language-skill>\n"
        + "                <subject-area>\n"
        + "                    <isced-f-code>0314</isced-f-code>\n"
        + "                </subject-area>\n"
        + "                <total-months-per-year>5</total-months-per-year>\n"
        + "                <blended>false</blended>\n"
        + "                <eqf-level>7</eqf-level>\n"
        + "                <eqf-level>8</eqf-level>\n"
        + "            </student-studies-mobility-spec>\n"
        + "\n"
        + "            <!-- Student mobility for traineeships. -->\n"
        + "            <student-traineeship-mobility-spec>\n"
        + "                <sending-hei-id>uw.edu.pl</sending-hei-id>\n"
        + "                <sending-ounit-id>140</sending-ounit-id>\n"
        + "                <receiving-hei-id>hibo.no</receiving-hei-id>\n"
        + "                <receiving-academic-year-id>2014/2015</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2015/2016</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2016/2017</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2017/2018</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2018/2019</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2019/2020</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2020/2021</receiving-academic-year-id>\n"
        + "                <mobilities-per-year>10</mobilities-per-year>\n"
        + "                <recommended-language-skill>\n"
        + "                    <language>no</language>\n"
        + "                    <cefr-level>B1</cefr-level>\n"
        + "                </recommended-language-skill>\n"
        + "                <subject-area>\n"
        + "                    <isced-f-code>0314</isced-f-code>\n"
        + "                </subject-area>\n"
        + "                <total-months-per-year>10</total-months-per-year>\n"
        + "                <blended>false</blended>\n"
        + "                <!-- No eqf-level for traineeships. -->\n"
        + "            </student-traineeship-mobility-spec>\n"
        + "\n"
        + "            <!-- Staff mobility for teaching. -->\n"
        + "            <staff-teacher-mobility-spec>\n"
        + "                <sending-hei-id>uw.edu.pl</sending-hei-id>\n"
        + "                <sending-ounit-id>140</sending-ounit-id>\n"
        + "                <receiving-hei-id>hibo.no</receiving-hei-id>\n"
        + "                <receiving-academic-year-id>2016/2017</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2017/2018</receiving-academic-year-id>\n"
        + "                <mobilities-per-year>2</mobilities-per-year>\n"
        + "                <recommended-language-skill>\n"
        + "                    <language>en</language>\n"
        + "                    <cefr-level>C1</cefr-level>\n"
        + "                </recommended-language-skill>\n"
        + "                <subject-area>\n"
        + "                    <isced-f-code>0314</isced-f-code>\n"
        + "                </subject-area>\n"
        + "                <!-- Staff mobilities have days instead of months. -->\n"
        + "                <total-days-per-year>8</total-days-per-year>\n"
        + "            </staff-teacher-mobility-spec>\n"
        + "            <staff-teacher-mobility-spec>\n"
        + "                <!-- Every specification describes a unidirectional mobility. If students or\n"
        + "                staff members are exchanged in both directions, two specifications are provided.\n"
        + "                (The same is true for every other *-mobility-spec element.) -->\n"
        + "                <sending-hei-id>hibo.no</sending-hei-id>\n"
        + "                <receiving-hei-id>uw.edu.pl</receiving-hei-id>\n"
        + "                <receiving-ounit-id>140</receiving-ounit-id>\n"
        + "                <receiving-academic-year-id>2016/2017</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2017/2018</receiving-academic-year-id>\n"
        + "                <mobilities-per-year>2</mobilities-per-year>\n"
        + "                <recommended-language-skill>\n"
        + "                    <language>en</language>\n"
        + "                    <cefr-level>C1</cefr-level>\n"
        + "                </recommended-language-skill>\n"
        + "                <subject-area>\n"
        + "                    <isced-f-code>0314</isced-f-code>\n"
        + "                </subject-area>\n"
        + "                <total-days-per-year>14</total-days-per-year>\n"
        + "            </staff-teacher-mobility-spec>\n"
        + "\n"
        + "            <!-- Staff mobility for training. -->\n"
        + "            <staff-training-mobility-spec>\n"
        + "                <sending-hei-id>hibo.no</sending-hei-id>\n"
        + "                <receiving-hei-id>uw.edu.pl</receiving-hei-id>\n"
        + "                <receiving-ounit-id>140</receiving-ounit-id>\n"
        + "                <receiving-academic-year-id>2016/2017</receiving-academic-year-id>\n"
        + "                <receiving-academic-year-id>2017/2018</receiving-academic-year-id>\n"
        + "                <mobilities-per-year>2</mobilities-per-year>\n"
        + "                <recommended-language-skill>\n"
        + "                    <language>en</language>\n"
        + "                    <cefr-level>B2</cefr-level>\n"
        + "                </recommended-language-skill>\n"
        + "                <receiving-contact>\n"
        + "                    <c:contact-name>Sylwia Nowak</c:contact-name>\n"
        + "                    <c:person-given-names>Sylwia</c:person-given-names>\n"
        + "                    <c:person-family-name>Nowak</c:person-family-name>\n"
        + "                    <c:email>email@example.com</c:email>\n"
        + "                    <!-- All other Abstract Contact fields are allowed too (including the role\n"
        + "                    description). -->\n"
        + "                </receiving-contact>\n"
        + "                <subject-area>\n"
        + "                    <isced-f-code>0314</isced-f-code>\n"
        + "                </subject-area>\n"
        + "                <sending-contact>\n"
        + "                    <c:contact-name>Sylwia Nowak</c:contact-name>\n"
        + "                    <c:person-given-names>Sylwia</c:person-given-names>\n"
        + "                    <c:person-family-name>Nowak</c:person-family-name>\n"
        + "                    <c:email>email@example.com</c:email>\n"
        + "                    <!-- All other Abstract Contact fields are allowed too (including the role\n"
        + "                    description). -->\n"
        + "                </sending-contact>\n"
        + "                <total-days-per-year>14</total-days-per-year>\n"
        + "            </staff-training-mobility-spec>\n"
        + "        </cooperation-conditions>\n"
        + "        <conditions-hash>7c045bc4ca23b3b9953adb27374aa27dcd41cfdda74fff9d2240a813a80443ae</conditions-hash>\n"
        + "        <!-- For clarity, we do not paste a real PDF binary here. This should be a signed PDF. The hei can choose to generate -->\n"
        + "        <!-- and sign its own PDF or use (sign and serve here) a document served by the partner. -->\n"
        + "        <pdf>MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmxt1dWM7wF18z9ZKd9IdolvVXPKYWsQo\n"
        + "            BE2fJXIXnwT2f39kKzCrNwRgia3XMdiS2jYHG0GAfqQfYNCafjIwhqI4d2pgjNNt11IUxViG</pdf>\n"
        + "    </iia>\n"
        + "\n"
        + "    <!-- More than one IIA can be returned in one response. We have only one here,\n"
        + "    to keep it simple. -->\n"
        + "\n"
        + "</iias-get-response>";

    // Act
    String hash = conditionsHashCalculator.calculateHashFor(iiaGetXml);

    // Assert
    assertThat(hash).isEqualTo("7c045bc4ca23b3b9953adb27374aa27dcd41cfdda74fff9d2240a813a80443ae");
  }

}